[variables]
NODE_VERSION = "22"

[[providers]]
name = "node"

[phases.setup]
nixPkgs = ["nodejs_22", "npm", "openssl"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "echo 'Starting build phase...' && rm -rf node_modules/.cache && npm ci --production=false && echo 'Dependencies installed' && npx prisma generate && echo 'Prisma generated' && npm run build && echo 'Build completed successfully'"

[start]
cmd = "npx prisma migrate deploy && npm start"